// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiActores;

#nullable disable

namespace WebApiActores.Migrations
{
    [DbContext(typeof(Negocio))]
    [Migration("20240815162717_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.33");

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.Property<int>("ListaAutoresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListaLibrosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListaAutoresId", "ListaLibrosId");

                    b.HasIndex("ListaLibrosId");

                    b.ToTable("AutorLibro");
                });

            modelBuilder.Entity("WebApiActores.Entitys.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("WebApiActores.Entitys.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreLibro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.HasOne("WebApiActores.Entitys.Autor", null)
                        .WithMany()
                        .HasForeignKey("ListaAutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiActores.Entitys.Libro", null)
                        .WithMany()
                        .HasForeignKey("ListaLibrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
