// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacagroup.Trade.Persistence.Context;

#nullable disable

namespace Pacagroup.Trade.Services.gRPC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("Pacagroup.Trade.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .HasPrecision(9)
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quanty")
                        .HasPrecision(9)
                        .HasColumnType("INTEGER");

                    b.Property<int>("Side")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TrasactionTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 522.5m,
                            Quanty = 1000,
                            Side = 0,
                            Symbol = "META",
                            TrasactionTime = new DateTime(2025, 2, 26, 18, 37, 16, 221, DateTimeKind.Local).AddTicks(6965),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 424.30m,
                            Quanty = 300,
                            Side = 0,
                            Symbol = "MSFT",
                            TrasactionTime = new DateTime(2025, 2, 26, 18, 37, 16, 221, DateTimeKind.Local).AddTicks(6983),
                            Type = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
