// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPIpeliculas;

#nullable disable

namespace MinimalAPIpeliculas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240805163128_Five")]
    partial class Five
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.GeneroPelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeliculaId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("GenerosPeliculas");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnCines")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaLanzamiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poster")
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Comentario", b =>
                {
                    b.HasOne("MinimalAPIpeliculas.Entitys.Pelicula", null)
                        .WithMany("ListaComentarios")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.GeneroPelicula", b =>
                {
                    b.HasOne("MinimalAPIpeliculas.Entitys.Genero", "Genero")
                        .WithMany("ListaGenerosPeliculas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalAPIpeliculas.Entitys.Pelicula", "Pelicula")
                        .WithMany("ListaGenerosPeliculas")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Pelicula", b =>
                {
                    b.HasOne("MinimalAPIpeliculas.Entitys.Actor", null)
                        .WithMany("ListaPeliculas")
                        .HasForeignKey("ActorId");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Actor", b =>
                {
                    b.Navigation("ListaPeliculas");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Genero", b =>
                {
                    b.Navigation("ListaGenerosPeliculas");
                });

            modelBuilder.Entity("MinimalAPIpeliculas.Entitys.Pelicula", b =>
                {
                    b.Navigation("ListaComentarios");

                    b.Navigation("ListaGenerosPeliculas");
                });
#pragma warning restore 612, 618
        }
    }
}
