// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducationDbContext))]
    [Migration("20241029142231_EducationMigracionInicial")]
    partial class EducationMigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.35");

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("39f850fc-7974-4194-8712-6de0a44a140f"),
                            Descripcion = "Curso de Testing",
                            FechaCreacion = new DateTime(2024, 10, 29, 11, 22, 31, 392, DateTimeKind.Local).AddTicks(2717),
                            FechaPublicacion = new DateTime(2024, 10, 30, 11, 22, 31, 392, DateTimeKind.Local).AddTicks(2729),
                            Precio = 33m,
                            Titulo = "Testing Master"
                        },
                        new
                        {
                            CursoId = new Guid("e64500bd-5aa4-4a2e-bb67-3cdee1d9cb63"),
                            Descripcion = "Curso de Java",
                            FechaCreacion = new DateTime(2024, 10, 29, 11, 22, 31, 392, DateTimeKind.Local).AddTicks(2736),
                            FechaPublicacion = new DateTime(2024, 10, 30, 11, 22, 31, 392, DateTimeKind.Local).AddTicks(2737),
                            Precio = 60m,
                            Titulo = "Java Master"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
